### PR TITLE
🐛Run build-compile-commands on extension start

### PR DESCRIPTION
**Pull request by BennyBot**
Does what the title says

### CODE REVIEW

**Comment by baylessj** [comment]
I get the following output when running this branch: 
```
pros build-compile-commands
sh-3.2$ pros build-compile-commands
sh: pros: command not found
sh-3.2
sh-3.2$ 
```

I have PROS installed through the one-click installation. It doesn't seem that PROS is ever put on my path, not sure if that's intentional or not. If we want to keep the CLI off the PATH then this command will need updated to point directly to the install location.

**Comment by baylessj** [comment]
Interestingly, despite this command failing, the try/catch clause does not raise any errors. My guess is that the `terminal.sendCommand` function doesn't propagate up any errors from the command being run.

**Comment by HotelCalifornia** [comment]
I presume it needs to specify the full path the the one click install if that's how it's installed...and maybe also worth verifying the cwd of the command

**Comment by baylessj** [comment]
Digging into this a bit further, [this function `paths`](https://github.com/purduesigbots/pros-vsc/blob/0a484d81a0cac44142adec0250f28d4a05b26a67/src/one-click/install.ts#L198) looks to be setting up a dedicated PROS terminal instance that _should_ have the one-click CLI and associated tools set on the terminal's PATH so we can simply run commands as `pros` rather than specifying the whole path to the PROS executable. I'll take a look as to what's keeping that from working on my system

**Comment by HotelCalifornia** [comment]
I don't think the sendCommand function uses the integrated terminal we've set up and iirc this is by design

**Comment by baylessj** [comment]
> It should be running through integrated terminal as we are calling `makeTerminal` just before, which sets up environment variables spawns the terminal we send commands to. Also the try/catch is not going to do anything because there is no way to recieve the output of `terminal.sendText`. When you got the error was the active terminal called PROS Terminal?

Yes, the terminal that contained the error message I posted is named "PROS Terminal".

**Comment by baylessj** [comment]
Ah, I think I've found the issue. The `paths` function that sets the PROS CLI location to PATH, among other things, is `async` while the main extension's `activate` method is synchronous. If we hit the `makeTerminal` call on line 69 prior to `paths` completing in the background then the PROS Terminal instance never gets the updated PATH.

@BennyBot I don't want to hijack your PR, but since I'm already in the weeds on this issue, would you be opposed to me opening up a separate PR that fixes this issue with running `build-compile-commands` on start and that cleans up the async/sync stuff here?

**Pull request closed without merging**
