### PR TITLE
Setup for Store Release

### PR DESCRIPTION
**Pull request by kunwarsahni01**
Just adding license, changelog, package info for store, and removing SVGs. Also testing PR CI.

### CODE REVIEW

**Comment by WillXuCodes** [comment]
Do you have a screenshot of the home page? I feel like we could also add that to our README to help with our storefront. (also should probably check to confirm that the png looks good)

**Comment by HotelCalifornia** [comment]
> Do you have a screenshot of the home page? I feel like we could also add that to our README to help with our storefront. (also should probably check to confirm that the png looks good)

If by home page you mean the one inside vs code when our extension is running then I agree

**Comment by WillXuCodes** [comment]
> > Do you have a screenshot of the home page? I feel like we could also add that to our README to help with our storefront. (also should probably check to confirm that the png looks good)
> 
> If by home page you mean the one inside vs code when our extension is running then I agree

yep

**Comment by kunwarsahni01** [comment]
> > > Do you have a screenshot of the home page? I feel like we could also add that to our README to help with our storefront. (also should probably check to confirm that the png looks good)
> > 
> > 
> > If by home page you mean the one inside vs code when our extension is running then I agree
> 
> yep

Not Yet, I can add it when the Welcome Screen is finished

**Comment by kunwarsahni01** [comment]
Can update README later.

**Pull request merged**
